### ISSUE TITLE
Error with Prediction

### ISSUE THREAD

**Issue by rieck074** [petersonR/sparseR#3]
Calling predict() using a sparseR model on new data which does not include the outcome variable ('Y') used in training returns the following error:

Error in `tidyr::drop_na()`:
! Problem while evaluating `tidyselect::all_of(columns)`.
Caused by error in `tidyselect::all_of()`:
! Can't subset elements that don't exist.
✖ Element `Y` doesn't exist.
Backtrace:
  1. stats::predict(sparse_mod, newdata = X4, at = "cvmin")
 30. tidyselect::all_of(columns)

**Comment by petersonR** [comment]
I think this has been fixed in the most recent commit. Please let me know if you still run into issues.
